// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAItW9EAXuW7orSd_PU1_dOhCo_glnma5s',
    appId: '1:75024762434:web:98aa5cc0c17c451f320fdb',
    messagingSenderId: '75024762434',
    projectId: 'spenzy-7dc2e',
    authDomain: 'spenzy-7dc2e.firebaseapp.com',
    storageBucket: 'spenzy-7dc2e.appspot.com',
    measurementId: 'G-GLSD94MM8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuIJnXR0-o2ydIYkQabVJJleFHybDE73o',
    appId: '1:75024762434:android:1798f98de07c6967320fdb',
    messagingSenderId: '75024762434',
    projectId: 'spenzy-7dc2e',
    storageBucket: 'spenzy-7dc2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmc7XGlcXw-2aVM0KGiROvuguIuuplhEg',
    appId: '1:75024762434:ios:d622f259fa6fe0b6320fdb',
    messagingSenderId: '75024762434',
    projectId: 'spenzy-7dc2e',
    storageBucket: 'spenzy-7dc2e.appspot.com',
    iosBundleId: 'com.example.spenzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmc7XGlcXw-2aVM0KGiROvuguIuuplhEg',
    appId: '1:75024762434:ios:a73bca3682c0181b320fdb',
    messagingSenderId: '75024762434',
    projectId: 'spenzy-7dc2e',
    storageBucket: 'spenzy-7dc2e.appspot.com',
    iosBundleId: 'com.example.spenzy.RunnerTests',
  );
}
